name: ML Pipeline CI

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib seaborn joblib
        
    - name: Set MLflow tracking URI
      run: |
        echo "MLFLOW_TRACKING_URI=file:///tmp/mlruns" >> $GITHUB_ENV
        
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --no-conda -P data_path=MLProject/namadataset_preprocessing/iris_preprocessed.csv -P tune_hyperparameters=true
        
    - name: Prepare artifacts for upload
      run: |
        mkdir -p artifacts
        cp -r /tmp/mlruns/* artifacts/
        
    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: mlflow-artifacts
        path: artifacts/
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iris-classification:latest
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
