name: iris-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.19.0
    - scikit-learn>=1.7.0
    - pandas
    - numpy
    - Flask>=2.0.0
    - gunicorn>=20.1.0
